### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by zoharargaman** [rnbguy/subscene-dl#2]
installed via Pip3
$ subscene 'I.May.Destroy.You.S01E06.720p.AMZN.WEBRip.x264-GalaxyTV.mkv'
then got this
Traceback (most recent call last):
  File "/usr/local/bin/subscene", line 5, in <module>
    from subscene import main
  File "/usr/local/lib/python3.8/site-packages/subscene/__init__.py", line 1, in <module>
    from .subscene import *
  File "/usr/local/lib/python3.8/site-packages/subscene/subscene.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PupikMac:~ zoharargaman$ subscene I.May.Destroy.You.S01E06.720p.AMZN.WEBRip.x264-GalaxyTV.mkv
Traceback (most recent call last):
  File "/usr/local/bin/subscene", line 5, in <module>
    from subscene import main
  File "/usr/local/lib/python3.8/site-packages/subscene/__init__.py", line 1, in <module>
    from .subscene import *
  File "/usr/local/lib/python3.8/site-packages/subscene/subscene.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by rnbguy** [comment]
Reinstall now with `pip3 install -U git+https://github.com/rnbdev/subscene-dl`
